name = "todoist-things-sync"
main = "src/index.ts"
compatibility_date = "2025-07-25"

[vars]
TODOIST_API_URL = "https://api.todoist.com/rest/v2"
# Generate a secure token with: openssl rand -hex 32
REPAIR_AUTH_TOKEN = "0e46c0c05c13b4d62991c3968b375c64c0dd6aba4470d505d305baa3112c052b"

# KV namespace for storing sync metadata and ID mappings
[[kv_namespaces]]
binding = "SYNC_METADATA"
id = "63e1a66560e24129bfe0915501554381"

# Run `wrangler secret put TODOIST_API_TOKEN` to set your token

# Cron triggers for scheduled sync operations
[triggers]
crons = ["*/2 * * * *"]  # Run every 2 minutes